[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions_ota.csv
lib_ldf_mode = deep+
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  knolleary/PubSubClient @ ^2.8
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^4.0.4
build_flags =
  -std=gnu++17
  -D BREWESP_FIRMWARE_VERSION=\"0.2.0-dev\"
