[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = partitions_ota.csv
lib_ldf_mode = deep+
build_flags =
  -D BREWESP_FW_VERSION=\"0.2.0-dev\"
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  knolleary/PubSubClient @ ^2.8
  paulstoffregen/OneWire @ ^2.3.8
  milesburton/DallasTemperature @ ^4.0.4

[env:native-tests]
platform = native
test_framework = unity
test_build_src = false
build_flags =
  -I test/support
  -I src
